version: '3.8'
services:
  # service Node JS
  app:
    container_name: api_to_to_list
    build:
      context: ./
      dockerfile: ./dockerfile.yml
    env_file:
      - ./backend/.env
    ports:
      - "3000"
    depends_on:
      - mysqldb
      - adminer
  # Service Nginx, to http. + file nginx.config in backend/config
  nginx:
    container_name: nginx_api_to_to_list
    image: nginx:alpine
    restart: always
    env_file: 
      - .env
    environment:
      - NGINX_HOST=${NGINX_HOST}
      - NGINX_PORT=${NGINX_PORT}
    ports:
    # <host port> : <container port>
      - "8080:80"
      - "443:443"
    volumes:
      - ./backend/config/nginx:/etc/nginx/conf.d
      - ./index.html:/var/www/html/index.html
      # ./backend/config/letsencrypt:/backend/config/letsencrypt:ro
      # ./certbot/data:/var/www/certbot
    command: [nginx-debug, '-g', 'daemon off;']
  # image for https
  # certbot:
  #   container_name: certbot
  #   image: certbot/certbot
  #   env_file:
  #     - ./backend/.env
  #   depends_on:
  #     - nginx
  #   command: >-
  #            certonly --reinstall --webroot --webroot-path=/var/www/certbot
  #            --email ${EMAIL} --agree-tos --no-eff-email
  #            -d ${DOMAIN}
  #   volumes:
  #     - ./backend/config/letsencrypt:/backend/config/letsencrypt
  #     - ./certbot/data:/var/www/
  # image MySql doc :https://hub.docker.com/_/mysql
  mysqldb:
    container_name: mysql
    env_file:
      - path: .env
        required: true # default
    image: mysql:8.0.35
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval:  10s
      timeout:  5s
      retries:  5
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DBROOT}
      - MYSQL_DATABASE=${DATABASE}
      - MYSQL_USER=${USER}
      - MYSQL_PASSWORD=${PASSWORD}
    ports:
      - "3306"
    depends_on:
      - nginx
    volumes:
      - ./to_do_list.sql:/docker-entrypoint-initdb.d/1.sql
      - db_data:/var/lib/mysql
  # service Adminer
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    environment:  
      ADMINER_DEFAULT_SERVER: mysqldb
    ports:
      - "8080"
    depends_on:
      - mysqldb
    env_file:
      - .env
volumes:
  db_data: {}