# In this docker fil, we need to create an environment to use the API on different support. 

# What do we need in the environment ?
# - node js version 20.9.0, mysql version 8.3.30
# Do I need a linux ?

# Docker image of Node Js
FROM node:20.9.0

# to define the repository to work
WORKDIR /backend

# copy of the package.json file and instal dependancies (source - dest)
COPY package.json ./package.json
RUN npm install

# copy of others files from project
COPY src ./src
COPY ../conception/base-de-données ./scripts

# eec scripts to create database
CMD [ "sh", "-c", "./scripts/create-db.sh && npm start" ]
