version: '3.8'
services:
  # service Node JS
  app:
    build: .
    ports:
      -"8080:8080"
    depends_on:
      - mysqldb
      - adminer
    env_file:
      - .env
  # Service Nginx, to http. + file nginx.config in backend/config
  nginx:
    image: nginx:alpine:3.17
    restart : always
    environment:
      - NGINX_HOST=${NGINX_HOST}
      - NGINX_PORT=${NGINX_PORT}
    ports:
    # <host port> : <container port>
      -"80:80"
      -"443:443"
    volumes:
      - .backend/config/nginx:/etc/nginx/conf.d
  # image for https
  certbot:
    image: certbot/certbot
    volumes:
      ./backend/config/conf:/etc/letsencrypt
      ./backend/config/www:/var/www/certbot
  # image MySql doc :https://hub.docker.com/_/mysql
  mysqldb:
    image: mysql:8.0.35
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DBROOT}
      - MYSQL_DATABASE=${DATABASE}
      - MYSQL_USER = ${USER}
      - MYSQL_PASSWORD= ${PASSWORD}
    ports:
      -"3306":"3306"
    depends_on:
      - nginx
    volumes:
      -db_data:/var/lib/mysql
  # service Adminer
  adminer:
    image: dockette/adminer:full-php5
    restart: always
    ports:
      -"8081":"8080"
    depends_on:
      - mysqldb
volumes:
  db_date: {}